openapi: 3.1.0
info:
  title: Equix API
  version: "0.1.0"
  description: "API для извлечения информации из PDF-документов с научными статьями."
servers:
  - url: http://localhost:8000
    description: Локальный сервер разработки
paths:
  /layout-extraction:
    post:
      summary: Извлечение разметки из документа
      description: Принимает PDF-документ и возвращает разметку (layout).
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: "Токен для аутентификации (если требуется)."
                document:
                  type: string
                  format: binary
                  description: "PDF-документ для анализа."
              required:
                - document
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  layout:
                    type: object
                    description: JSON-структура разметки документа.
                  document_id:
                    type: string
                    description: Идентификатор документа.
        "400":
          description: "Ошибка: Неправильный запрос"
  /graphics-extraction:
    post:
      summary: Извлечение графической информации
      description: Извлечение данных из графиков и таблиц по заданной области разметки.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: "Токен для аутентификации (если требуется)."
                document_id:
                  type: string
                  description: "Идентификатор документа."
                layout_block_id:
                  type: integer
                  description: "Идентификатор блока разметки."
                output_type:
                  type: string
                  description: "Формат результата (например, Markdown)."
              required:
                - document_id
                - layout_block_id
                - output_type
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: "Статус выполнения."
                  text:
                    type: string
                    description: "Результат извлечения."
        "400":
          description: "Ошибка: Неправильный запрос"
  /information-extraction:
    post:
      summary: Извлечение информации
      description: Отвечает на вопрос по документу, используя его содержимое.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: "Токен для аутентификации (если требуется)."
                document_id:
                  type: string
                  description: "Идентификатор документа."
                prompt:
                  type: string
                  description: "Вопрос о содержимом документа."
              required:
                - document_id
                - prompt
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: "Статус выполнения."
                  answer:
                    type: string
                    description: "Результат извлечения информации."
        "400":
          description: "Ошибка: Неправильный запрос"
